package com.babata.chip.repository.entity;

import java.util.Date;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.nickname
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.authority
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Byte authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.avatar
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.register_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.nickname
     *
     * @return the value of admin.nickname
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.nickname
     *
     * @param nickname the value for admin.nickname
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.authority
     *
     * @return the value of admin.authority
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Byte getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.authority
     *
     * @param authority the value for admin.authority
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setAuthority(Byte authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.avatar
     *
     * @return the value of admin.avatar
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.avatar
     *
     * @param avatar the value for admin.avatar
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.register_date
     *
     * @return the value of admin.register_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.register_date
     *
     * @param registerDate the value for admin.register_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}