package com.babata.chip.repository.entity;

import java.util.Date;

public class ArticleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.en_title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String enTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.subtitle
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tag
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content_md
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String contentMd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content_html
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String contentHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content_text
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String contentText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.permission
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Byte permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.cover_image
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.read_count
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.en_title
     *
     * @return the value of article.en_title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getEnTitle() {
        return enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.en_title
     *
     * @param enTitle the value for article.en_title
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle == null ? null : enTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.subtitle
     *
     * @return the value of article.subtitle
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.subtitle
     *
     * @param subtitle the value for article.subtitle
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tag
     *
     * @return the value of article.tag
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tag
     *
     * @param tag the value for article.tag
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content_md
     *
     * @return the value of article.content_md
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getContentMd() {
        return contentMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content_md
     *
     * @param contentMd the value for article.content_md
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setContentMd(String contentMd) {
        this.contentMd = contentMd == null ? null : contentMd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content_html
     *
     * @return the value of article.content_html
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getContentHtml() {
        return contentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content_html
     *
     * @param contentHtml the value for article.content_html
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setContentHtml(String contentHtml) {
        this.contentHtml = contentHtml == null ? null : contentHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content_text
     *
     * @return the value of article.content_text
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getContentText() {
        return contentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content_text
     *
     * @param contentText the value for article.content_text
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setContentText(String contentText) {
        this.contentText = contentText == null ? null : contentText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.permission
     *
     * @return the value of article.permission
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Byte getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.permission
     *
     * @param permission the value for article.permission
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setPermission(Byte permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.cover_image
     *
     * @return the value of article.cover_image
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.cover_image
     *
     * @param coverImage the value for article.cover_image
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.read_count
     *
     * @return the value of article.read_count
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.read_count
     *
     * @param readCount the value for article.read_count
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.modify_time
     *
     * @return the value of article.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.modify_time
     *
     * @param modifyTime the value for article.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}