package com.babata.chip.repository.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BalanceChangeLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.change_num
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private BigDecimal changeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.remark
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.before_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private BigDecimal beforeBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.after_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private BigDecimal afterBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_change_log.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.id
     *
     * @return the value of balance_change_log.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.id
     *
     * @param id the value for balance_change_log.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.user_id
     *
     * @return the value of balance_change_log.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.user_id
     *
     * @param userId the value for balance_change_log.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.order_id
     *
     * @return the value of balance_change_log.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.order_id
     *
     * @param orderId the value for balance_change_log.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.change_num
     *
     * @return the value of balance_change_log.change_num
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public BigDecimal getChangeNum() {
        return changeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.change_num
     *
     * @param changeNum the value for balance_change_log.change_num
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setChangeNum(BigDecimal changeNum) {
        this.changeNum = changeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.type
     *
     * @return the value of balance_change_log.type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.type
     *
     * @param type the value for balance_change_log.type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.remark
     *
     * @return the value of balance_change_log.remark
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.remark
     *
     * @param remark the value for balance_change_log.remark
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.before_balance
     *
     * @return the value of balance_change_log.before_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public BigDecimal getBeforeBalance() {
        return beforeBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.before_balance
     *
     * @param beforeBalance the value for balance_change_log.before_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setBeforeBalance(BigDecimal beforeBalance) {
        this.beforeBalance = beforeBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.after_balance
     *
     * @return the value of balance_change_log.after_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public BigDecimal getAfterBalance() {
        return afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.after_balance
     *
     * @param afterBalance the value for balance_change_log.after_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setAfterBalance(BigDecimal afterBalance) {
        this.afterBalance = afterBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.create_time
     *
     * @return the value of balance_change_log.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.create_time
     *
     * @param createTime the value for balance_change_log.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_change_log.modify_time
     *
     * @return the value of balance_change_log.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_change_log.modify_time
     *
     * @param modifyTime the value for balance_change_log.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}