package com.babata.chip.repository.entity;

import java.util.Date;

public class BomDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.category_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long chipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String partNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.quantity
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.unit_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.total_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bom.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.id
     *
     * @return the value of bom.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.id
     *
     * @param id the value for bom.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.manufacturer
     *
     * @return the value of bom.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.manufacturer
     *
     * @param manufacturer the value for bom.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.category_name
     *
     * @return the value of bom.category_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.category_name
     *
     * @param categoryName the value for bom.category_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.chip_id
     *
     * @return the value of bom.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getChipId() {
        return chipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.chip_id
     *
     * @param chipId the value for bom.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setChipId(Long chipId) {
        this.chipId = chipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.part_number
     *
     * @return the value of bom.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.part_number
     *
     * @param partNumber the value for bom.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.quantity
     *
     * @return the value of bom.quantity
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.quantity
     *
     * @param quantity the value for bom.quantity
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.unit_price
     *
     * @return the value of bom.unit_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.unit_price
     *
     * @param unitPrice the value for bom.unit_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.total_price
     *
     * @return the value of bom.total_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.total_price
     *
     * @param totalPrice the value for bom.total_price
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.create_time
     *
     * @return the value of bom.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.create_time
     *
     * @param createTime the value for bom.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bom.modify_time
     *
     * @return the value of bom.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bom.modify_time
     *
     * @param modifyTime the value for bom.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}