package com.babata.chip.repository.entity;

import java.util.Date;

public class ChipCompareRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.first_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String firstChipPartNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.second_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String secondChipPartNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.file_list
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String fileList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.prompt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String prompt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.api_supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String apiSupplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.model
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.input_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer inputTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.output_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer outputTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.duration
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.cost
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.result
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip_compare_record.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.id
     *
     * @return the value of chip_compare_record.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.id
     *
     * @param id the value for chip_compare_record.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.user_id
     *
     * @return the value of chip_compare_record.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.user_id
     *
     * @param userId the value for chip_compare_record.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.first_chip_part_number
     *
     * @return the value of chip_compare_record.first_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getFirstChipPartNumber() {
        return firstChipPartNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.first_chip_part_number
     *
     * @param firstChipPartNumber the value for chip_compare_record.first_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setFirstChipPartNumber(String firstChipPartNumber) {
        this.firstChipPartNumber = firstChipPartNumber == null ? null : firstChipPartNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.second_chip_part_number
     *
     * @return the value of chip_compare_record.second_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getSecondChipPartNumber() {
        return secondChipPartNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.second_chip_part_number
     *
     * @param secondChipPartNumber the value for chip_compare_record.second_chip_part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setSecondChipPartNumber(String secondChipPartNumber) {
        this.secondChipPartNumber = secondChipPartNumber == null ? null : secondChipPartNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.file_list
     *
     * @return the value of chip_compare_record.file_list
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getFileList() {
        return fileList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.file_list
     *
     * @param fileList the value for chip_compare_record.file_list
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setFileList(String fileList) {
        this.fileList = fileList == null ? null : fileList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.status
     *
     * @return the value of chip_compare_record.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.status
     *
     * @param status the value for chip_compare_record.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.prompt
     *
     * @return the value of chip_compare_record.prompt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.prompt
     *
     * @param prompt the value for chip_compare_record.prompt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt == null ? null : prompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.api_supplier
     *
     * @return the value of chip_compare_record.api_supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getApiSupplier() {
        return apiSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.api_supplier
     *
     * @param apiSupplier the value for chip_compare_record.api_supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setApiSupplier(String apiSupplier) {
        this.apiSupplier = apiSupplier == null ? null : apiSupplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.model
     *
     * @return the value of chip_compare_record.model
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.model
     *
     * @param model the value for chip_compare_record.model
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.input_tokens
     *
     * @return the value of chip_compare_record.input_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getInputTokens() {
        return inputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.input_tokens
     *
     * @param inputTokens the value for chip_compare_record.input_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setInputTokens(Integer inputTokens) {
        this.inputTokens = inputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.output_tokens
     *
     * @return the value of chip_compare_record.output_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getOutputTokens() {
        return outputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.output_tokens
     *
     * @param outputTokens the value for chip_compare_record.output_tokens
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setOutputTokens(Integer outputTokens) {
        this.outputTokens = outputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.duration
     *
     * @return the value of chip_compare_record.duration
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.duration
     *
     * @param duration the value for chip_compare_record.duration
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.cost
     *
     * @return the value of chip_compare_record.cost
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.cost
     *
     * @param cost the value for chip_compare_record.cost
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.result
     *
     * @return the value of chip_compare_record.result
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.result
     *
     * @param result the value for chip_compare_record.result
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.create_time
     *
     * @return the value of chip_compare_record.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.create_time
     *
     * @param createTime the value for chip_compare_record.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip_compare_record.modify_time
     *
     * @return the value of chip_compare_record.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip_compare_record.modify_time
     *
     * @param modifyTime the value for chip_compare_record.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}