package com.babata.chip.repository.entity;

import java.util.Date;

public class ChipDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String partNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.sheet_url
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String sheetUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.parameter
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String parameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chip.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.id
     *
     * @return the value of chip.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.id
     *
     * @param id the value for chip.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.manufacturer
     *
     * @return the value of chip.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.manufacturer
     *
     * @param manufacturer the value for chip.manufacturer
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.part_number
     *
     * @return the value of chip.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.part_number
     *
     * @param partNumber the value for chip.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.description
     *
     * @return the value of chip.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.description
     *
     * @param description the value for chip.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.sheet_url
     *
     * @return the value of chip.sheet_url
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getSheetUrl() {
        return sheetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.sheet_url
     *
     * @param sheetUrl the value for chip.sheet_url
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setSheetUrl(String sheetUrl) {
        this.sheetUrl = sheetUrl == null ? null : sheetUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.parameter
     *
     * @return the value of chip.parameter
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.parameter
     *
     * @param parameter the value for chip.parameter
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setParameter(String parameter) {
        this.parameter = parameter == null ? null : parameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.create_time
     *
     * @return the value of chip.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.create_time
     *
     * @param createTime the value for chip.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chip.modify_time
     *
     * @return the value of chip.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chip.modify_time
     *
     * @param modifyTime the value for chip.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}