package com.babata.chip.repository.entity;

import java.util.Date;

public class MajorSegmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_segment.id
     *
     * @return the value of major_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_segment.id
     *
     * @param id the value for major_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_segment.name
     *
     * @return the value of major_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_segment.name
     *
     * @param name the value for major_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_segment.description
     *
     * @return the value of major_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_segment.description
     *
     * @param description the value for major_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_segment.create_time
     *
     * @return the value of major_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_segment.create_time
     *
     * @param createTime the value for major_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_segment.modify_time
     *
     * @return the value of major_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_segment.modify_time
     *
     * @param modifyTime the value for major_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}