package com.babata.chip.repository.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentOrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.amount
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.alipay_trade_no
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String alipayTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.product_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.notify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date notifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.id
     *
     * @return the value of payment_order.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.id
     *
     * @param id the value for payment_order.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.order_id
     *
     * @return the value of payment_order.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.order_id
     *
     * @param orderId the value for payment_order.order_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.user_id
     *
     * @return the value of payment_order.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.user_id
     *
     * @param userId the value for payment_order.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.amount
     *
     * @return the value of payment_order.amount
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.amount
     *
     * @param amount the value for payment_order.amount
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.status
     *
     * @return the value of payment_order.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.status
     *
     * @param status the value for payment_order.status
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.alipay_trade_no
     *
     * @return the value of payment_order.alipay_trade_no
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getAlipayTradeNo() {
        return alipayTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.alipay_trade_no
     *
     * @param alipayTradeNo the value for payment_order.alipay_trade_no
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setAlipayTradeNo(String alipayTradeNo) {
        this.alipayTradeNo = alipayTradeNo == null ? null : alipayTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.product_name
     *
     * @return the value of payment_order.product_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.product_name
     *
     * @param productName the value for payment_order.product_name
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.notify_time
     *
     * @return the value of payment_order.notify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.notify_time
     *
     * @param notifyTime the value for payment_order.notify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.create_time
     *
     * @return the value of payment_order.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.create_time
     *
     * @param createTime the value for payment_order.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order.modify_time
     *
     * @return the value of payment_order.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order.modify_time
     *
     * @param modifyTime the value for payment_order.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}