package com.babata.chip.repository.entity;

import java.util.Date;

public class Pin2PinDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long chipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String partNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.supplier_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String supplierP2p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.part_number_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String partNumberP2p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pin2pin.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.id
     *
     * @return the value of pin2pin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.id
     *
     * @param id the value for pin2pin.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.chip_id
     *
     * @return the value of pin2pin.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getChipId() {
        return chipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.chip_id
     *
     * @param chipId the value for pin2pin.chip_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setChipId(Long chipId) {
        this.chipId = chipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.supplier
     *
     * @return the value of pin2pin.supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.supplier
     *
     * @param supplier the value for pin2pin.supplier
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.part_number
     *
     * @return the value of pin2pin.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.part_number
     *
     * @param partNumber the value for pin2pin.part_number
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.supplier_p2p
     *
     * @return the value of pin2pin.supplier_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getSupplierP2p() {
        return supplierP2p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.supplier_p2p
     *
     * @param supplierP2p the value for pin2pin.supplier_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setSupplierP2p(String supplierP2p) {
        this.supplierP2p = supplierP2p == null ? null : supplierP2p.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.part_number_p2p
     *
     * @return the value of pin2pin.part_number_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPartNumberP2p() {
        return partNumberP2p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.part_number_p2p
     *
     * @param partNumberP2p the value for pin2pin.part_number_p2p
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPartNumberP2p(String partNumberP2p) {
        this.partNumberP2p = partNumberP2p == null ? null : partNumberP2p.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.create_time
     *
     * @return the value of pin2pin.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.create_time
     *
     * @param createTime the value for pin2pin.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pin2pin.modify_time
     *
     * @return the value of pin2pin.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pin2pin.modify_time
     *
     * @param modifyTime the value for pin2pin.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}