package com.babata.chip.repository.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Pin2PinDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Pin2PinDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChipIdIsNull() {
            addCriterion("chip_id is null");
            return (Criteria) this;
        }

        public Criteria andChipIdIsNotNull() {
            addCriterion("chip_id is not null");
            return (Criteria) this;
        }

        public Criteria andChipIdEqualTo(Long value) {
            addCriterion("chip_id =", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdNotEqualTo(Long value) {
            addCriterion("chip_id <>", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdGreaterThan(Long value) {
            addCriterion("chip_id >", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdGreaterThanOrEqualTo(Long value) {
            addCriterion("chip_id >=", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdLessThan(Long value) {
            addCriterion("chip_id <", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdLessThanOrEqualTo(Long value) {
            addCriterion("chip_id <=", value, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdIn(List<Long> values) {
            addCriterion("chip_id in", values, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdNotIn(List<Long> values) {
            addCriterion("chip_id not in", values, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdBetween(Long value1, Long value2) {
            addCriterion("chip_id between", value1, value2, "chipId");
            return (Criteria) this;
        }

        public Criteria andChipIdNotBetween(Long value1, Long value2) {
            addCriterion("chip_id not between", value1, value2, "chipId");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("supplier like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("supplier not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNull() {
            addCriterion("part_number is null");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNotNull() {
            addCriterion("part_number is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumberEqualTo(String value) {
            addCriterion("part_number =", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotEqualTo(String value) {
            addCriterion("part_number <>", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThan(String value) {
            addCriterion("part_number >", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThanOrEqualTo(String value) {
            addCriterion("part_number >=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThan(String value) {
            addCriterion("part_number <", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThanOrEqualTo(String value) {
            addCriterion("part_number <=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLike(String value) {
            addCriterion("part_number like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotLike(String value) {
            addCriterion("part_number not like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberIn(List<String> values) {
            addCriterion("part_number in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotIn(List<String> values) {
            addCriterion("part_number not in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberBetween(String value1, String value2) {
            addCriterion("part_number between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotBetween(String value1, String value2) {
            addCriterion("part_number not between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pIsNull() {
            addCriterion("supplier_p2p is null");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pIsNotNull() {
            addCriterion("supplier_p2p is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pEqualTo(String value) {
            addCriterion("supplier_p2p =", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pNotEqualTo(String value) {
            addCriterion("supplier_p2p <>", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pGreaterThan(String value) {
            addCriterion("supplier_p2p >", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_p2p >=", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pLessThan(String value) {
            addCriterion("supplier_p2p <", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pLessThanOrEqualTo(String value) {
            addCriterion("supplier_p2p <=", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pLike(String value) {
            addCriterion("supplier_p2p like", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pNotLike(String value) {
            addCriterion("supplier_p2p not like", value, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pIn(List<String> values) {
            addCriterion("supplier_p2p in", values, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pNotIn(List<String> values) {
            addCriterion("supplier_p2p not in", values, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pBetween(String value1, String value2) {
            addCriterion("supplier_p2p between", value1, value2, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andSupplierP2pNotBetween(String value1, String value2) {
            addCriterion("supplier_p2p not between", value1, value2, "supplierP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pIsNull() {
            addCriterion("part_number_p2p is null");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pIsNotNull() {
            addCriterion("part_number_p2p is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pEqualTo(String value) {
            addCriterion("part_number_p2p =", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pNotEqualTo(String value) {
            addCriterion("part_number_p2p <>", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pGreaterThan(String value) {
            addCriterion("part_number_p2p >", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pGreaterThanOrEqualTo(String value) {
            addCriterion("part_number_p2p >=", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pLessThan(String value) {
            addCriterion("part_number_p2p <", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pLessThanOrEqualTo(String value) {
            addCriterion("part_number_p2p <=", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pLike(String value) {
            addCriterion("part_number_p2p like", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pNotLike(String value) {
            addCriterion("part_number_p2p not like", value, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pIn(List<String> values) {
            addCriterion("part_number_p2p in", values, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pNotIn(List<String> values) {
            addCriterion("part_number_p2p not in", values, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pBetween(String value1, String value2) {
            addCriterion("part_number_p2p between", value1, value2, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andPartNumberP2pNotBetween(String value1, String value2) {
            addCriterion("part_number_p2p not between", value1, value2, "partNumberP2p");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pin2pin
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 14 23:13:54 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}