package com.babata.chip.repository.entity;

import java.util.Date;

public class SessionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.title
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.uuid
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.end_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.id
     *
     * @return the value of session.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.id
     *
     * @param id the value for session.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.user_id
     *
     * @return the value of session.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.user_id
     *
     * @param userId the value for session.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.title
     *
     * @return the value of session.title
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.title
     *
     * @param title the value for session.title
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.uuid
     *
     * @return the value of session.uuid
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.uuid
     *
     * @param uuid the value for session.uuid
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.create_time
     *
     * @return the value of session.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.create_time
     *
     * @param createTime the value for session.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.modify_time
     *
     * @return the value of session.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.modify_time
     *
     * @param modifyTime the value for session.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.end_time
     *
     * @return the value of session.end_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.end_time
     *
     * @param endTime the value for session.end_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}