package com.babata.chip.repository.entity;

import java.util.Date;

public class SubSegmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.major_segment_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Long majorSegmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.id
     *
     * @return the value of sub_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.id
     *
     * @param id the value for sub_segment.id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.name
     *
     * @return the value of sub_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.name
     *
     * @param name the value for sub_segment.name
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.major_segment_id
     *
     * @return the value of sub_segment.major_segment_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Long getMajorSegmentId() {
        return majorSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.major_segment_id
     *
     * @param majorSegmentId the value for sub_segment.major_segment_id
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setMajorSegmentId(Long majorSegmentId) {
        this.majorSegmentId = majorSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.description
     *
     * @return the value of sub_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.description
     *
     * @param description the value for sub_segment.description
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.create_time
     *
     * @return the value of sub_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.create_time
     *
     * @param createTime the value for sub_segment.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_segment.modify_time
     *
     * @return the value of sub_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_segment.modify_time
     *
     * @param modifyTime the value for sub_segment.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}