package com.babata.chip.repository.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserBalanceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.total_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private BigDecimal totalBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.total_cnt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer totalCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.charge_type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Byte chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_balance.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.id
     *
     * @return the value of user_balance.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.id
     *
     * @param id the value for user_balance.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.user_id
     *
     * @return the value of user_balance.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.user_id
     *
     * @param userId the value for user_balance.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.total_balance
     *
     * @return the value of user_balance.total_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public BigDecimal getTotalBalance() {
        return totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.total_balance
     *
     * @param totalBalance the value for user_balance.total_balance
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setTotalBalance(BigDecimal totalBalance) {
        this.totalBalance = totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.total_cnt
     *
     * @return the value of user_balance.total_cnt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getTotalCnt() {
        return totalCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.total_cnt
     *
     * @param totalCnt the value for user_balance.total_cnt
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setTotalCnt(Integer totalCnt) {
        this.totalCnt = totalCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.charge_type
     *
     * @return the value of user_balance.charge_type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Byte getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.charge_type
     *
     * @param chargeType the value for user_balance.charge_type
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setChargeType(Byte chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.version
     *
     * @return the value of user_balance.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.version
     *
     * @param version the value for user_balance.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.create_time
     *
     * @return the value of user_balance.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.create_time
     *
     * @param createTime the value for user_balance.create_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_balance.modify_time
     *
     * @return the value of user_balance.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_balance.modify_time
     *
     * @param modifyTime the value for user_balance.modify_time
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}