package com.babata.chip.repository.entity;

import java.util.Date;

public class VisitorDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.ip
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.uri
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visit_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private Date visitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.platform
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.browser
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.location
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.id
     *
     * @return the value of visitor.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.id
     *
     * @param id the value for visitor.id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.ip
     *
     * @return the value of visitor.ip
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.ip
     *
     * @param ip the value for visitor.ip
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.uri
     *
     * @return the value of visitor.uri
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.uri
     *
     * @param uri the value for visitor.uri
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.user_id
     *
     * @return the value of visitor.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.user_id
     *
     * @param userId the value for visitor.user_id
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visit_date
     *
     * @return the value of visitor.visit_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visit_date
     *
     * @param visitDate the value for visitor.visit_date
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.platform
     *
     * @return the value of visitor.platform
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.platform
     *
     * @param platform the value for visitor.platform
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.browser
     *
     * @return the value of visitor.browser
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.browser
     *
     * @param browser the value for visitor.browser
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.version
     *
     * @return the value of visitor.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.version
     *
     * @param version the value for visitor.version
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.location
     *
     * @return the value of visitor.location
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.location
     *
     * @param location the value for visitor.location
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}