package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.AdminDO;
import com.babata.chip.repository.entity.AdminDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(AdminDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(AdminDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<AdminDO> selectByExample(AdminDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    AdminDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") AdminDO record, @Param("example") AdminDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") AdminDO record, @Param("example") AdminDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(AdminDO record);
}