package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.ArticleDO;
import com.babata.chip.repository.entity.ArticleDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    long countByExample(ArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int deleteByExample(ArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int insert(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int insertSelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    List<ArticleDO> selectByExample(ArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    ArticleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByExampleSelective(@Param("record") ArticleDO record, @Param("example") ArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByExample(@Param("record") ArticleDO record, @Param("example") ArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByPrimaryKeySelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByPrimaryKey(ArticleDO record);
}