package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.BalanceChangeLogDO;
import com.babata.chip.repository.entity.BalanceChangeLogDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(BalanceChangeLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(BalanceChangeLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(BalanceChangeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(BalanceChangeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<BalanceChangeLogDO> selectByExample(BalanceChangeLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    BalanceChangeLogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") BalanceChangeLogDO record, @Param("example") BalanceChangeLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") BalanceChangeLogDO record, @Param("example") BalanceChangeLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(BalanceChangeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_change_log
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(BalanceChangeLogDO record);
}