package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.ChipCompareRecordDO;
import com.babata.chip.repository.entity.ChipCompareRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChipCompareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(ChipCompareRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(ChipCompareRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(ChipCompareRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(ChipCompareRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<ChipCompareRecordDO> selectByExample(ChipCompareRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    ChipCompareRecordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") ChipCompareRecordDO record, @Param("example") ChipCompareRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") ChipCompareRecordDO record, @Param("example") ChipCompareRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(ChipCompareRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chip_compare_record
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(ChipCompareRecordDO record);
}