package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.LoginDO;
import com.babata.chip.repository.entity.LoginDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(LoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(LoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(LoginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(LoginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<LoginDO> selectByExample(LoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    LoginDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") LoginDO record, @Param("example") LoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") LoginDO record, @Param("example") LoginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(LoginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(LoginDO record);
}