package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.MajorSegmentDO;
import com.babata.chip.repository.entity.MajorSegmentDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorSegmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(MajorSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(MajorSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(MajorSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(MajorSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<MajorSegmentDO> selectByExample(MajorSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    MajorSegmentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") MajorSegmentDO record, @Param("example") MajorSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") MajorSegmentDO record, @Param("example") MajorSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(MajorSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_segment
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(MajorSegmentDO record);
}