package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.MessageDO;
import com.babata.chip.repository.entity.MessageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<MessageDO> selectByExample(MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    MessageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") MessageDO record, @Param("example") MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") MessageDO record, @Param("example") MessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(MessageDO record);
}