package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.PaymentOrderDO;
import com.babata.chip.repository.entity.PaymentOrderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(PaymentOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(PaymentOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(PaymentOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(PaymentOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<PaymentOrderDO> selectByExample(PaymentOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    PaymentOrderDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") PaymentOrderDO record, @Param("example") PaymentOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") PaymentOrderDO record, @Param("example") PaymentOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(PaymentOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_order
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(PaymentOrderDO record);
}