package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.Pin2PinDO;
import com.babata.chip.repository.entity.Pin2PinDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Pin2PinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(Pin2PinDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(Pin2PinDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(Pin2PinDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(Pin2PinDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<Pin2PinDO> selectByExample(Pin2PinDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    Pin2PinDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") Pin2PinDO record, @Param("example") Pin2PinDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") Pin2PinDO record, @Param("example") Pin2PinDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(Pin2PinDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pin2pin
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(Pin2PinDO record);
}