package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.SessionDO;
import com.babata.chip.repository.entity.SessionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(SessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(SessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(SessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(SessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<SessionDO> selectByExample(SessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    SessionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") SessionDO record, @Param("example") SessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") SessionDO record, @Param("example") SessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(SessionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(SessionDO record);
}