package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.SubSegmentDO;
import com.babata.chip.repository.entity.SubSegmentDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubSegmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    long countByExample(SubSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int deleteByExample(SubSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int insert(SubSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int insertSelective(SubSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    List<SubSegmentDO> selectByExample(SubSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    SubSegmentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByExampleSelective(@Param("record") SubSegmentDO record, @Param("example") SubSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByExample(@Param("record") SubSegmentDO record, @Param("example") SubSegmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByPrimaryKeySelective(SubSegmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_segment
     *
     * @mbg.generated Sun Dec 14 23:13:53 CST 2025
     */
    int updateByPrimaryKey(SubSegmentDO record);
}