package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.UserBalanceDO;
import com.babata.chip.repository.entity.UserBalanceDOExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.math.BigDecimal;
import java.util.List;

public interface UserBalanceMapper {
    @Update("UPDATE user_balance " +
            "SET total_balance = total_balance - #{amount}, " +
            "    version = version + 1, " +
            "    modify_time = NOW() " +
            "WHERE user_id = #{userId} " +
            "  AND total_balance >= #{amount} " +
            "  AND charge_type = 0")
    int deductBalance(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    long countByExample(UserBalanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int deleteByExample(UserBalanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int insert(UserBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int insertSelective(UserBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    List<UserBalanceDO> selectByExample(UserBalanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    UserBalanceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int updateByExampleSelective(@Param("record") UserBalanceDO record, @Param("example") UserBalanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int updateByExample(@Param("record") UserBalanceDO record, @Param("example") UserBalanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int updateByPrimaryKeySelective(UserBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance
     *
     * @mbg.generated Sun Dec 14 21:53:30 CST 2025
     */
    int updateByPrimaryKey(UserBalanceDO record);
}