package com.babata.chip.repository.mapper;

import com.babata.chip.repository.entity.VisitorDO;
import com.babata.chip.repository.entity.VisitorDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    long countByExample(VisitorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByExample(VisitorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insert(VisitorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int insertSelective(VisitorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    List<VisitorDO> selectByExample(VisitorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    VisitorDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExampleSelective(@Param("record") VisitorDO record, @Param("example") VisitorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByExample(@Param("record") VisitorDO record, @Param("example") VisitorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKeySelective(VisitorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Sun Dec 14 23:13:54 CST 2025
     */
    int updateByPrimaryKey(VisitorDO record);
}